# Generated by Django 5.2.4 on 2025-08-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Future", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="daily_order_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
