# Generated by Django 5.2.4 on 2025-08-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Future", "0003_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
